### PR TITLE
Book from guest

### PR DESCRIPTION
**Pull request by a-quelle**
It is now possible to make a booking from the guest list. The guest is autofilled.

### CODE REVIEW

**Review by capgeminiKoen — CHANGES_REQUESTED** [review]
There is a weird bug when selecting a Guest after using this form to add it. The implementation is quite clunky as is, we have to discuss about a better way

**Comment by a-quelle** [comment]
Fixed all bugs

**Comment by a-quelle** [comment]
Fixed all bugs, please review again.

**Comment by capgeminiKoen** [comment]
The correct guest is not selected in the booking form. please adjust

**Comment by a-quelle** [comment]
Adjusted

**Pull request merged**
